name: flutter_pagination_code_snippet
description: 페이지네이션 기능을 MVVM 적용하기 위해 스터디

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  json_serializable: ^6.2.0
  convex_bottom_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/